### ISSUE TITLE
[QUESTION] Is this project in active development ?

### ISSUE THREAD

**Issue by drupalshift** [Emulair/Emulair-Android#81]
Hey there! It's great to see someone carrying the torch from Lemuroid. 
Just curious, is this project still ongoing? I really hope so. 
Lemuroid was/is an awesome multi-emulator, but things slowed down quite a bit, and you've already achieved so much with this.

I've been checking out your upcoming features list and backlog, and there are some really wonderful things in there. This could be massive and might even surpass Lemuroid's legacy!

I'd love to support this project in any way I can, but I was wondering if it's still active and accepting help.

**Comment by drupalshift** [comment]
Hey there!

Wow, I'm super excited to hear from you and even more thrilled to know that Emulair is coming along! 😊 I've been there juggling university, work, and passion projects. Hats off to you!

I'm a bit of a C++ guru, but I've been getting my feet wet with Android development lately. Can't wait to dive in and see how I can chip in with Emulair. I'm ready to tackle the learning curve and put my skills to good use in the project.

Your approach to handling contributions and offering feedback is awesome. It's not just about building Emulair, but also about growing a public repo and learning from each other, right?

I'm super eager to send over my first pull request and join in on this adventure. Good luck with your final year! I'm sure once that's out of the way, you'll be doing even more amazing stuff with Emulair.

Thanks a ton for this cool opportunity! Looking forward to contributing and chatting more in the pull requests!

**Comment by drupalshift** [comment]
P.S. I've been thinking about how we can really make Emulair shine by learning from Lemuroid. It's got some great strengths that we should definitely embrace. But, I also see an opportunity for us to improve on some of its cons.

For instance, we could set up clear contribution guidelines, making it super easy for anyone to jump in. A detailed 'how to build the project' guide would be a huge help too. Plus, focusing a bit more on commenting and documentation could really make a difference.

I've noticed that most devs don't have the time to sift through and understand every aspect of a new project. So, if we lay down some solid foundation work, we could make it way more comfortable for others to contribute. It's all about making their journey in Emulair as smooth and enjoyable as possible!

Speaking of growing, I've got a bit of a knack for marketing too! Once we've got a version you're happy with, how about we jazz things up with a cool landing page, get the buzz going on Product Hunt, Reddit, and other places? I think it's a great way to drum up some excitement and get people talking.

Also, I was thinking, we could take a peek at the most commented issues and Reddit threads around the Lemuroid project. It could give us some valuable insights into what users are really looking for and help us fine-tune Emulair even more.

**Comment by RaduBratan** [comment]
> I'll see if I can write some short contribution guides by the end of next week to more easily expand on them in the future.

Done!

> I'll update [the features list] with all the other features/bugs collected from community input.

Done!

Thank you again for your suggestions!
